/**:
  ros__parameters:
    color_range_list:
      black:
        max:
        - 86
        - 187
        - 196
        min:
        - 0
        - 30
        - 92
      blue:
        max:
        - 158
        - 178
        - 117
        min:
        - 47
        - 95
        - 46
      green:
        max:
        - 196
        - 111
        - 255
        min:
        - 0
        - 46
        - 104
      red:
        max:
        - 255
        - 255
        - 255
        min:
        - 0
        - 0
        - 151
      tennis:
        max:
        - 210
        - 159
        - 255
        min:
        - 31
        - 66
        - 178
      white:
        max:
        - 255
        - 155
        - 155
        min:
        - 111
        - 100
        - 100
      yellow:
        max:
        - 255
        - 177
        - 184
        min:
        - 195
        - 110
        - 146
