depth:
  offset:
  - 0.0
  - 0.0
  - 0.0
  scale:
  - 1.0
  - 1.0
  - 1.0
kinematics:
  offset:
  - 0.003
  - -0.008
  - 0.006
  scale:
  - 1.0
  - 1.0
  - 1.0
pixel:
  offset:
  - 0.003
  - 0.015
  - -0.002
  scale:
  - 1.0
  - 1.01
  - 1.0
